### ISSUE TITLE
interface with ir.export

### ISSUE THREAD

**Issue by rvalyi** [akretion/connector-nosql#5]
Extend ir.export so that it can define a Solerp export.
The export DSL should be generated from the ir.export and its ir.export.line.
checkboxes for +/- for functional fields or export suffixes could be added in ir.export.line.

For ir.export, we should also register the listener: on the object itself, but also, back to the object for any included o2m record or m2o record. Also eventually for m2m records.

**Comment by sebastienbeau** [comment]
done
